#!/bin/bash

#/ NAME
#/     meh -- alox demo
#/
#/ SYNOPSIS
#/     meh ...

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "_jason"

# entry point
function main {
  echo "$@"
}

main "$@"
